// <auto-generated />
using System;
using System.Collections.Generic;
using Kariyer.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kariyer.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260509180750_AddAccountDeletionSagaActiveUserConstraint")]
    partial class AddAccountDeletionSagaActiveUserConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kariyer.Identity.Domain.Entities.AccountDeletionSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledByUid")
                        .HasColumnType("text")
                        .HasColumnName("cancelled_by_uid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_state");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("GracePeriodEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grace_period_ends_at");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initiated_by");

                    b.Property<string>("InitiatedByUid")
                        .HasColumnType("text")
                        .HasColumnName("initiated_by_uid");

                    b.Property<DateTimeOffset?>("SupabaseBannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("supabase_banned_at");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_type");

                    b.Property<string>("UserUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_uid");

                    b.HasKey("CorrelationId");

                    b.HasIndex("UserUid")
                        .IsUnique()
                        .HasDatabaseName("uix_account_deletion_saga_state_active_user")
                        .HasFilter("current_state NOT IN ('Deleted', 'Cancelled')");

                    b.HasIndex("CurrentState", "GracePeriodEndsAt")
                        .HasDatabaseName("ix_account_deletion_saga_state_grace_period");

                    b.ToTable("account_deletion_saga_state", "identity");
                });

            modelBuilder.Entity("Kariyer.Identity.Domain.Entities.LegacyAdmin", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("text")
                        .HasColumnName("uid");

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("address");

                    b.Property<string>("AdminRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("admin")
                        .HasColumnName("admin_role");

                    b.Property<string>("BackgroundUrl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("background_url");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailHash")
                        .HasColumnType("text")
                        .HasColumnName("email_hash");

                    b.Property<DateTime?>("EmailUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_update");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<string>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Erkek")
                        .HasColumnName("gender");

                    b.Property<bool>("IsAccountCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_account_completed");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.PrimitiveCollection<string[]>("Jwt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new string[0])
                        .HasColumnName("jwt");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NationalIdHash")
                        .HasColumnType("text")
                        .HasColumnName("national_id_hash");

                    b.Property<string>("Neighbourhood")
                        .HasColumnType("text")
                        .HasColumnName("neighbourhood");

                    b.PrimitiveCollection<string[]>("Notifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new string[0])
                        .HasColumnName("notifications");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_expires_at");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_update");

                    b.Property<bool>("PermaDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("perma_deleted");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneHash")
                        .HasColumnType("text")
                        .HasColumnName("phone_hash");

                    b.Property<DateTime?>("PhoneUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_update");

                    b.Property<bool>("PhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_verified");

                    b.Property<string>("PhotoUrl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("photo_url");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("Race")
                        .HasColumnType("text")
                        .HasColumnName("race");

                    b.Property<string>("Surname")
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("title");

                    b.Property<string>("Town")
                        .HasColumnType("text")
                        .HasColumnName("town");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<DateTime?>("UsernameUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_update");

                    b.Property<string>("VerificationCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("verification_code");

                    b.Property<DateTime?>("VerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_code_expires_at");

                    b.HasKey("Uid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("admin", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Kariyer.Identity.Domain.Entities.LegacyCompany", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("text")
                        .HasColumnName("uid");

                    b.PrimitiveCollection<List<string>>("AffiliatedCompanies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("affiliated_companies");

                    b.Property<string>("Approved")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("registered")
                        .HasColumnName("approved");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.PrimitiveCollection<List<string>>("ApprovedEmployees")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("approved_employees");

                    b.Property<string>("AuthorizedName")
                        .HasColumnType("text")
                        .HasColumnName("authorized_name");

                    b.Property<string>("AuthorizedSurname")
                        .HasColumnType("text")
                        .HasColumnName("authorized_surname");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("text")
                        .HasColumnName("background_url");

                    b.Property<bool>("CommercialConsentAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("commercial_consent_accepted");

                    b.Property<string>("CompanyDesc")
                        .HasColumnType("text")
                        .HasColumnName("company_desc");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyWebsite")
                        .HasColumnType("text")
                        .HasColumnName("company_website");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.PrimitiveCollection<List<string>>("DeletedEmployees")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("deleted_employees");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.PrimitiveCollection<List<int>>("DownloadedCv")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("downloaded_cv");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailHash")
                        .HasColumnType("text")
                        .HasColumnName("email_hash");

                    b.Property<DateTimeOffset?>("EmailUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_update");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("EmployeeCount")
                        .HasColumnType("text")
                        .HasColumnName("employee_count");

                    b.PrimitiveCollection<List<string>>("Employees")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("employees");

                    b.Property<bool>("EmploymentOffice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("employment_office");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.PrimitiveCollection<List<string>>("Followers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("followers");

                    b.Property<string>("FoundedYear")
                        .HasColumnType("text")
                        .HasColumnName("founded_year");

                    b.Property<string>("Industry")
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<string>("Instagram")
                        .HasColumnType("text")
                        .HasColumnName("instagram");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text")
                        .HasColumnName("instagram_url");

                    b.Property<bool>("IsAccountCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_account_completed");

                    b.Property<bool>("IsCivilian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_civilian");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.PrimitiveCollection<List<string>>("Jwt")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("jwt");

                    b.Property<bool>("KvkkAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("kvkk_accepted");

                    b.Property<string>("Linkedin")
                        .HasColumnType("text")
                        .HasColumnName("linkedin");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("MailDomain")
                        .HasColumnType("text")
                        .HasColumnName("mail_domain");

                    b.Property<string>("Neighbourhood")
                        .HasColumnType("text")
                        .HasColumnName("neighbourhood");

                    b.PrimitiveCollection<List<string>>("Notifications")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("notifications");

                    b.Property<int>("OnboardingReminderStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("onboarding_reminder_step");

                    b.Property<string>("OnesignalPlayerId")
                        .HasColumnType("text")
                        .HasColumnName("onesignal_player_id");

                    b.PrimitiveCollection<List<string>>("ParentCompanies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parent_companies");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("PasswordResetBlockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_blocked_until");

                    b.Property<int>("PasswordResetCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("password_reset_count");

                    b.Property<DateTimeOffset?>("PasswordResetLastAttempt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_last_attempt");

                    b.PrimitiveCollection<List<string>>("PendingReceivedRequests")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("pending_received_requests");

                    b.PrimitiveCollection<List<string>>("PendingSentRequests")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("pending_sent_requests");

                    b.Property<bool>("PermaDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("perma_deleted");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneHash")
                        .HasColumnType("text")
                        .HasColumnName("phone_hash");

                    b.Property<DateTimeOffset?>("PhoneUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_update");

                    b.Property<bool>("PhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_verified");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.PrimitiveCollection<List<string>>("Plan")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("plan");

                    b.Property<int>("PriorityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority_score");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("text")
                        .HasColumnName("rejected_by");

                    b.PrimitiveCollection<List<string>>("RejectedEmployees")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("rejected_employees");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.PrimitiveCollection<List<int>>("SeenCv")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("seen_cv");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<string>>("SubCompanies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sub_companies");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TaxCertificateUrl")
                        .HasColumnType("text")
                        .HasColumnName("tax_certificate_url");

                    b.Property<string>("TaxIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_id_number");

                    b.Property<string>("TaxIdNumberHash")
                        .HasColumnType("text")
                        .HasColumnName("tax_id_number_hash");

                    b.Property<string>("TaxOffice")
                        .HasColumnType("text")
                        .HasColumnName("tax_office");

                    b.Property<string>("TaxOfficeProvince")
                        .HasColumnType("text")
                        .HasColumnName("tax_office_province");

                    b.Property<string>("Town")
                        .HasColumnType("text")
                        .HasColumnName("town");

                    b.Property<string>("Twitter")
                        .HasColumnType("text")
                        .HasColumnName("twitter");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("text")
                        .HasColumnName("twitter_url");

                    b.Property<bool>("UserAgreementAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("user_agreement_accepted");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<DateTimeOffset?>("UsernameUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_update");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("text")
                        .HasColumnName("verification_code");

                    b.Property<DateTimeOffset?>("VerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_code_expires_at");

                    b.HasKey("Uid");

                    b.ToTable("company", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Kariyer.Identity.Domain.Entities.LegacyEmployee", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("text")
                        .HasColumnName("uid");

                    b.Property<string>("Adress")
                        .HasColumnType("text")
                        .HasColumnName("adress");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("text")
                        .HasColumnName("background_url");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<bool>("CommercialConsentAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("commercial_consent_accepted");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("text")
                        .HasColumnName("company_email");

                    b.Property<int>("CompanyEmailOtpCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("company_email_otp_count");

                    b.Property<DateTimeOffset?>("CompanyEmailOtpExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("company_email_otp_expired_at");

                    b.Property<bool>("CompanyEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("company_email_verified");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("Describe")
                        .HasColumnType("text")
                        .HasColumnName("describe");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailHash")
                        .HasColumnType("text")
                        .HasColumnName("email_hash");

                    b.Property<DateTimeOffset?>("EmailUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_update");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.PrimitiveCollection<List<string>>("Followers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("followers");

                    b.PrimitiveCollection<List<string>>("Following")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("following");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsAccountCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_account_completed");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_rating");

                    b.PrimitiveCollection<List<string>>("Jwt")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("jwt");

                    b.Property<bool>("KvkkAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("kvkk_accepted");

                    b.Property<string>("LookingJob")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("0")
                        .HasColumnName("looking_job");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NationalId")
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<string>("NationalIdHash")
                        .HasColumnType("text")
                        .HasColumnName("national_id_hash");

                    b.Property<string>("Neighbourhood")
                        .HasColumnType("text")
                        .HasColumnName("neighbourhood");

                    b.PrimitiveCollection<List<string>>("Notifications")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("notifications");

                    b.Property<int>("OnboardingReminderStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("onboarding_reminder_step");

                    b.Property<string>("OnesignalPlayerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("onesignal_player_id");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("PasswordResetBlockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_blocked_until");

                    b.Property<int>("PasswordResetCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("password_reset_count");

                    b.Property<DateTimeOffset?>("PasswordResetLastAttempt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_last_attempt");

                    b.Property<bool>("PermaDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("perma_deleted");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneHash")
                        .HasColumnType("text")
                        .HasColumnName("phone_hash");

                    b.Property<DateTimeOffset?>("PhoneUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_update");

                    b.Property<bool>("PhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_verified");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("Race")
                        .HasColumnType("text")
                        .HasColumnName("race");

                    b.PrimitiveCollection<List<string>>("SelectedSkills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("selected_skills");

                    b.Property<string>("Surname")
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Town")
                        .HasColumnType("text")
                        .HasColumnName("town");

                    b.Property<bool>("UserAgreementAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("user_agreement_accepted");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<DateTimeOffset?>("UsernameUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_update");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("text")
                        .HasColumnName("verification_code");

                    b.Property<DateTimeOffset?>("VerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_code_expires_at");

                    b.Property<string>("WorkingType")
                        .HasColumnType("text")
                        .HasColumnName("working_type");

                    b.HasKey("Uid");

                    b.ToTable("employee", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("inbox_state", "identity");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("outbox_message", "identity");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("outbox_state", "identity");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
